# Generated by Django 2.1 on 2018-08-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyForm', '0002_auto_20180819_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='ph_no',
            new_name='ph',
        ),
    ]
