# Generated by Django 2.1 on 2018-08-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyForm', '0003_auto_20180819_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='emailid',
            new_name='email',
        ),
    ]
