# Generated by Django 2.1 on 2018-08-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyForm', '0004_auto_20180819_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='Data',
        ),
    ]
