# Generated by Django 2.1 on 2018-08-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyForm', '0005_auto_20180819_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='UserData',
        ),
    ]
